// <auto-generated />
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260923101801_AddGarageAndCarSeedData")]
    partial class AddGarageAndCarSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GarageId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GarageId = 1,
                            IsAvailable = true,
                            Make = "Audi",
                            Model = "A4",
                            Type = 1,
                            Year = 2016
                        },
                        new
                        {
                            Id = 2,
                            GarageId = 1,
                            IsAvailable = false,
                            Make = "BMW",
                            Model = "X5",
                            Type = 3,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            GarageId = 2,
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            Type = 1,
                            Year = 2018
                        },
                        new
                        {
                            Id = 4,
                            GarageId = 3,
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Mustang",
                            Type = 4,
                            Year = 2021
                        },
                        new
                        {
                            Id = 5,
                            GarageId = 2,
                            IsAvailable = false,
                            Make = "Tesla",
                            Model = "Model Y",
                            Type = 3,
                            Year = 2023
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Garages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "123 Main Street",
                            Name = "Downtown Motors"
                        },
                        new
                        {
                            Id = 2,
                            Location = "456 Oak Avenue",
                            Name = "Suburban Auto Hub"
                        },
                        new
                        {
                            Id = 3,
                            Location = "789 Speedway Blvd",
                            Name = "Elite Performance Center"
                        });
                });

            modelBuilder.Entity("GarageApp.Data.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Data.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Data.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
