// <auto-generated />
using System;
using CookBookApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookBookApp.Data.Migrations
{
    [DbContext(typeof(CookBookDbContext))]
    [Migration("20261008124539_EditedDeleteBehavior")]
    partial class EditedDeleteBehavior
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Breakfast"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Salad"
                        });
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Egg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Flour"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Milk"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sugar"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Butter"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Salt"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Spaghetti"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Minced Beef"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Tomato"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Olive Oil"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cucumber"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Feta Cheese"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Dark Chocolate"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Canned Tomatoes"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Onion"
                        });
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CookTime")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PrepTime")
                        .HasColumnType("int");

                    b.Property<int>("Servings")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CookTime = 15,
                            Instructions = "Whisk flour, milk, eggs, sugar and salt into a smooth batter. Fry ladlefuls in melted butter until golden on both sides.",
                            Name = "Classic Pancakes",
                            PrepTime = 10,
                            Servings = 4
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            CookTime = 60,
                            Instructions = "Fry the onion in olive oil, brown the beef, add the canned tomatoes and simmer for 45 minutes. Boil the spaghetti and serve with the sauce.",
                            Name = "Spaghetti Bolognese",
                            PrepTime = 15,
                            Servings = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            CookTime = 1,
                            Instructions = "Dice the tomatoes and cucumbers, dress with olive oil and salt, then top with grated feta cheese.",
                            Name = "Shopska Salad",
                            PrepTime = 10,
                            Servings = 4
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CookTime = 25,
                            Instructions = "Melt the chocolate with the butter, stir in sugar and eggs, fold in the flour. Bake at 180°C for about 25 minutes.",
                            Name = "Chocolate Brownies",
                            PrepTime = 15,
                            Servings = 12
                        });
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("MeasurementUnit")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(10, 3)");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipesIngredients");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            MeasurementUnit = 3,
                            Quantity = 200m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            MeasurementUnit = 1,
                            Quantity = 300m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            MeasurementUnit = 14,
                            Quantity = 2m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            MeasurementUnit = 6,
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            MeasurementUnit = 3,
                            Note = "melted",
                            Quantity = 30m
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 6,
                            MeasurementUnit = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            MeasurementUnit = 3,
                            Quantity = 400m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            MeasurementUnit = 3,
                            Quantity = 500m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 15,
                            MeasurementUnit = 14,
                            Note = "finely chopped",
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 14,
                            MeasurementUnit = 1,
                            Note = "400 g, crushed",
                            Quantity = 1000m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 10,
                            MeasurementUnit = 6,
                            Quantity = 2m
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 6,
                            MeasurementUnit = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 9,
                            MeasurementUnit = 14,
                            Note = "diced",
                            Quantity = 3m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 11,
                            MeasurementUnit = 14,
                            Note = "diced",
                            Quantity = 2m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 12,
                            MeasurementUnit = 3,
                            Note = "grated",
                            Quantity = 150m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 10,
                            MeasurementUnit = 6,
                            Quantity = 2m
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 6,
                            MeasurementUnit = 5,
                            Quantity = 1m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 13,
                            MeasurementUnit = 3,
                            Note = "chopped",
                            Quantity = 200m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 5,
                            MeasurementUnit = 3,
                            Quantity = 150m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 4,
                            MeasurementUnit = 3,
                            Quantity = 150m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 1,
                            MeasurementUnit = 14,
                            Quantity = 3m
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 2,
                            MeasurementUnit = 3,
                            Quantity = 100m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Recipe", b =>
                {
                    b.HasOne("CookBookApp.Data.Data.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.RecipeIngredient", b =>
                {
                    b.HasOne("CookBookApp.Data.Data.Models.Ingredient", "Ingredient")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookBookApp.Data.Data.Models.Recipe", "Recipe")
                        .WithMany("RecipesIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Ingredient", b =>
                {
                    b.Navigation("RecipesIngredients");
                });

            modelBuilder.Entity("CookBookApp.Data.Data.Models.Recipe", b =>
                {
                    b.Navigation("RecipesIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
